import { Route, Routes, Link, useLocation } from 'react-router-dom';
import { useEffect } from 'react';
import { ArrowRight, ArrowUpRight, Check, Clock3, MapPin, ShieldCheck } from 'lucide-react';
import { business, courses, imageUrl, images, services } from './data/business.js';
import { Button, CTASection, ContactForm, CourseCard, Gallery, Hero, ImagePanel, PageShell, ProcessSteps, Reveal, SectionTitle, ServiceCard, TrustStrip, wa } from './components.jsx';

function Home() {
  return <><Hero/><TrustStrip/><section className="welcome section-pad" id="welcome"><div className="welcome-copy"><SectionTitle eyebrow="A PRACTICAL PARTNER FOR THE ROAD AHEAD" title={<>Skills for the road.<br/><em>Support beyond it.</em></>} copy="From your first driving lesson to help with vehicle paperwork, God's Grace Mega Driving School Academy brings useful services together under one roof."/><Button to="/about" variant="dark">Meet the academy <ArrowRight size={16}/></Button></div><ImagePanel src={images.instructor} alt="Student smiling behind the wheel of a training car" label="A PRACTICAL APPROACH TO DRIVER TRAINING"/></section><DrivingPreview/><section className="services-home section-pad"><div className="section-row"><SectionTitle eyebrow="MORE WAYS WE CAN HELP" title="A little more than driving." copy="Explore practical support for the things that keep you moving."/><Button to="/services" variant="text">Explore all services <ArrowRight size={16}/></Button></div><div className="service-grid">{services.slice(0,3).map(([title,copy],i)=><ServiceCard key={title} title={title} copy={copy} index={i}/>)}</div><div className="service-extra"><div><span>VEHICLES</span><b>Buy or sell with confidence.</b><Link to="/vehicles">Explore vehicle services <ArrowUpRight size={16}/></Link></div><div><span>REAL ESTATE</span><b>Property. Investment. Opportunity.</b><Link to="/real-estate">Explore property services <ArrowUpRight size={16}/></Link></div></div></section><section className="approval section-pad"><div className="approval-badge"><ShieldCheck size={34}/><span>FRSC</span><small>APPROVED<br/>DRIVING SCHOOL</small></div><div><span className="eyebrow">A FOUNDATION OF TRUST</span><h2>Training with recognised approval.</h2><p>God's Grace Mega Driving School Academy is a Federal Government Approved Driving School with FRSC.</p><Button to="/about" variant="outline-dark">About our academy <ArrowRight size={16}/></Button></div></section><section className="gallery-section section-pad"><div className="section-row"><SectionTitle eyebrow="A LOOK AT THE ROAD AHEAD" title="Made for real life on the road."/><Button to="/contact" variant="text">Ask us a question <ArrowRight size={16}/></Button></div><Gallery/></section><CTASection/></>;
}
function DrivingPreview() { return <section className="driving-preview section-pad"><div className="section-row"><SectionTitle eyebrow="DRIVING SCHOOL" title="Find your way behind the wheel." copy="Choose manual or automatic lessons built around practical training, flexible timing and your availability."/><Button to="/driving-school" variant="dark">Explore driving school <ArrowRight size={16}/></Button></div><div className="course-grid">{courses.map(c=><CourseCard key={c.type} course={c}/>)}</div><div className="course-notes"><span><Clock3/> 2 weeks’ training</span><span><Check/> Flexible schedule</span><span><Check/> Minimum age 17+</span><span><Check/> Learner’s permit after completion, valid for 3 months</span></div></section>; }
function DrivingPage() { return <><PageHero eyebrow="DRIVING SCHOOL" title={<>Learn with purpose.<br/><em>Drive with confidence.</em></>} copy="Practical manual and automatic driving training in Lagos / Badagry, shaped around your schedule." image="manual"/><TrustStrip/><DrivingPreview/><section className="process-section section-pad"><SectionTitle eyebrow="YOUR TRAINING, STEP BY STEP" title="A clear path from first lesson to permit."/><ProcessSteps/><p className="fine-print">A learner’s permit is provided after successful training and lasts for 3 months.</p></section><CTASection title="Choose a course and get started."/></>; }
function PageHero({ eyebrow, title, copy, image }) { return <section className="page-hero"><div className="page-hero-copy"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{copy}</p><Button href={wa(`Hello, I would like to enquire about ${eyebrow.toLowerCase()}.`)} variant="gold">Make an enquiry <ArrowRight size={16}/></Button></div><div className="page-hero-photo"><img src={imageUrl(image,1400)} alt={`${eyebrow.toLowerCase()} in Lagos`} fetchPriority="high"/></div></section>; }
function ServicesPage() { return <><PageHero eyebrow="VEHICLE DOCUMENTATION" title={<>Documentation help,<br/><em>made more straightforward.</em></>} copy="Get guidance and processing support for common vehicle and driver documentation enquiries." image="automatic"/><section className="section-pad docs-section"><SectionTitle eyebrow="DOCUMENTATION ASSISTANCE" title="Support for the paperwork." copy="Tell us what you need and our team can guide you on the next steps."/><div className="service-grid service-grid-six">{services.map(([title,copy],i)=><ServiceCard key={title} title={title} copy={copy} index={i}/>)}</div></section><CTASection title="Need help with your documents?" copy="Message us on WhatsApp and tell us the documentation support you need."/></>; }
function VehiclesPage() { return <><PageHero eyebrow="VEHICLE SERVICES" title={<>Buy or sell<br/><em>with confidence.</em></>} copy="Enquire about vehicle sourcing or selling support. Tell us what you have in mind and we’ll take it from there." image="automatic"/><section className="vehicle-feature section-pad"><div><SectionTitle eyebrow="BUYING & SELLING" title="The right vehicle starts with the right conversation." copy="We support vehicle sourcing, vehicle sales and customer enquiries. Share your requirements or tell us about a vehicle you’d like to sell."/><Button href={wa('Hello, I would like to enquire about buying or selling a vehicle.')} variant="dark">Enquire about a vehicle <ArrowRight size={16}/></Button></div><div className="vehicle-image-card"><img src={imageUrl('vehicle')} alt="Vehicle shown in motion" loading="lazy"/><div><span>VEHICLE SERVICES</span><h3>Vehicle sourcing &amp; sales</h3><p>Contact us with your requirements to start an enquiry.</p><a href={wa('Hello, I would like to enquire about available vehicles.')} target="_blank" rel="noreferrer">Ask about vehicles <ArrowUpRight size={16}/></a></div></div></section><CTASection title="Looking for a vehicle?"/></>; }
function RealEstatePage() { return <><PageHero eyebrow="REAL ESTATE" title={<>Property. Investment.<br/><em>Opportunity.</em></>} copy="Connect with us for property agency, development and property enquiries." image="property"/><section className="property-section section-pad"><div className="property-copy"><SectionTitle eyebrow="PROPERTY SERVICES" title="Make your next property move with a local point of contact." copy="God's Grace Mega Driving School Academy also provides real estate agency and development services. Speak with us about your property enquiry."/><div className="property-points"><p><Check/> Real estate property agency</p><p><Check/> Property development</p><p><Check/> Property enquiries</p></div><Button href={wa('Hello, I would like to enquire about real estate services.')} variant="dark">Make a property enquiry <ArrowRight size={16}/></Button></div><div className="property-photo"><img src={imageUrl('property')} alt="Modern home exterior" loading="lazy"/><span>PROPERTY SERVICES · ENQUIRE WITH OUR TEAM</span></div></section><CTASection title="Have a property enquiry?" copy="Start a conversation with our team about agency, development or property services."/></>; }
function AboutPage() { return <><PageHero eyebrow="ABOUT THE ACADEMY" title={<>Good guidance for<br/><em>the road ahead.</em></>} copy="A Lagos / Badagry academy bringing driving training, documentation assistance and other practical services together." image="hero"/><section className="about-story section-pad"><ImagePanel src={images.practice} alt="Student practising behind the wheel" label="PRACTICAL TRAINING · LAGOS / BADAGRY"/><div><SectionTitle eyebrow="WHO WE ARE" title="One academy. Multiple ways to move forward." copy="God's Grace Mega Driving School Academy serves customers across Lagos / Badagry, Nigeria. Our work includes manual and automatic driving training, vehicle documentation support, vehicle buying and selling, and real estate agency and development."/><p className="about-approval"><ShieldCheck/> Federal Government Approved Driving School with FRSC</p><Button to="/contact" variant="dark">Talk to our team <ArrowRight size={16}/></Button></div></section><CTASection/></>; }
function ContactPage() { return <><PageHero eyebrow="CONTACT" title={<>Tell us what<br/><em>you need.</em></>} copy="Driving lessons, documentation, vehicles or property—our team is ready to hear from you." image="automatic"/><section className="contact-layout section-pad"><div className="contact-details"><SectionTitle eyebrow="LET’S TALK" title="A good next step starts with a conversation." copy="Contact God's Grace Mega Driving School Academy in Lagos / Badagry."/><div className="contact-detail"><Phone/><div><small>CALL US</small><a href={`tel:${business.phoneDisplay}`}>{business.phoneDisplay}</a></div></div><div className="contact-detail"><MapPin/><div><small>FIND US</small><b>{business.location}</b></div></div><Button href={wa('Hello God’s Grace Mega Driving School Academy, I would like to make an enquiry.')} variant="gold">Chat on WhatsApp <ArrowUpRight size={16}/></Button></div><div className="contact-form-wrap"><h3>Send an enquiry</h3><p>Choose a topic and we’ll open WhatsApp with your message ready.</p><ContactForm/></div></section><section className="contact-note"><span>GOD’S GRACE MEGA DRIVING SCHOOL ACADEMY</span><p>Driving school · Vehicle documentation · Vehicle services · Real estate</p></section></>; }
function NotFound() { return <section className="not-found"><span className="eyebrow">PAGE NOT FOUND</span><h1>Let’s get you back on the road.</h1><Button to="/" variant="dark">Return home <ArrowRight size={16}/></Button></section>; }
const pageMeta = {
  '/': ["God's Grace Mega Driving School Academy | Lagos & Badagry", 'Manual and automatic driving lessons, vehicle documentation assistance and more in Lagos / Badagry, Nigeria.'],
  '/driving-school': ['Driving School in Lagos & Badagry | God’s Grace Mega', 'Book manual or automatic driving lessons in Lagos / Badagry. Two week training with flexible scheduling.'],
  '/services': ['Vehicle Documentation Assistance | Lagos', 'Get assistance with vehicle registration, driver’s licence processing, renewals and tinted permit enquiries in Lagos.'],
  '/vehicles': ['Vehicle Buying & Selling | God’s Grace Mega', 'Enquire about vehicle sourcing and vehicle sales support in Lagos / Badagry.'],
  '/real-estate': ['Real Estate Services | Lagos & Badagry', 'Property agency, development and real estate enquiries with God’s Grace Mega Driving School Academy.'],
  '/about': ['About the Academy | God’s Grace Mega', 'Learn about our driving training, vehicle documentation support, vehicle services and real estate work.'],
  '/contact': ['Contact | God’s Grace Mega Driving School Academy', 'Contact our team in Lagos / Badagry for driving lessons, vehicle documents, vehicle or property enquiries.'],
};
function RouteMetadata() {
  const { pathname } = useLocation();
  useEffect(() => {
    const [title, description] = pageMeta[pathname] || ['Page not found | God’s Grace Mega', 'The requested page could not be found.'];
    document.title = title;
    let meta = document.querySelector('meta[name="description"]');
    if (!meta) { meta = document.createElement('meta'); meta.name = 'description'; document.head.appendChild(meta); }
    meta.content = description;
  }, [pathname]);
  return null;
}
export default function App() { return <><RouteMetadata/><PageShell><Routes><Route path="/" element={<Home/>}/><Route path="/driving-school" element={<DrivingPage/>}/><Route path="/services" element={<ServicesPage/>}/><Route path="/vehicles" element={<VehiclesPage/>}/><Route path="/real-estate" element={<RealEstatePage/>}/><Route path="/about" element={<AboutPage/>}/><Route path="/contact" element={<ContactPage/>}/><Route path="*" element={<NotFound/>}/></Routes></PageShell></>; }
