import { useState } from 'react';
import { Link, NavLink, useLocation } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, CarFront, Check, ClipboardList, Clock3, House, Menu, ShieldCheck, X } from 'lucide-react';
import { business, imageUrl } from './data/business.js';

export const wa = (message) => business.whatsapp(message);
export function Button({ to, href, children, variant = 'dark', className = '', ...props }) {
  const cls = `button button-${variant} ${className}`;
  return to ? <Link className={cls} to={to} {...props}>{children}</Link> : <a className={cls} href={href || wa()} target={href?.startsWith('http') ? '_blank' : undefined} rel="noreferrer" {...props}>{children}</a>;
}
export function Reveal({ children, className = '', delay = 0 }) {
  return <motion.div className={className} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.12 }} transition={{ duration: 0.55, delay, ease: [0.22, 1, 0.36, 1] }}>{children}</motion.div>;
}
export function SectionTitle({ eyebrow, title, copy, light = false }) {
  return <Reveal className={`section-title ${light ? 'light' : ''}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2>{copy && <p>{copy}</p>}</Reveal>;
}
const links = [['Home', '/'], ['Driving School', '/driving-school'], ['Services', '/services'], ['About', '/about'], ['Vehicles', '/vehicles'], ['Real Estate', '/real-estate'], ['Contact', '/contact']];
export function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="navbar"><Link to="/" className="brand" onClick={() => setOpen(false)}><span className="brand-mark">GG</span><span><b>GOD’S GRACE MEGA</b><small>DRIVING SCHOOL ACADEMY</small></span></Link><button className="menu-toggle" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button><nav className={open ? 'nav-links open' : 'nav-links'} aria-label="Main navigation">{links.map(([label, path]) => <NavLink key={path} to={path} onClick={() => setOpen(false)}>{label}</NavLink>)}<Button to="/contact" className="nav-cta">Book a Lesson <ArrowUpRight size={15}/></Button></nav></header>;
}
export function Footer() {
  return <footer className="footer"><div className="footer-main"><div><Link to="/" className="brand footer-brand"><span className="brand-mark">GG</span><span><b>GOD’S GRACE MEGA</b><small>DRIVING SCHOOL ACADEMY</small></span></Link><p>Practical driving education and vehicle services for Lagos and Badagry.</p></div><div className="footer-col"><b>Explore</b>{links.slice(1, 6).map(([l, p]) => <Link key={p} to={p}>{l}</Link>)}</div><div className="footer-col"><b>Get in touch</b><span>{business.location}</span><a href={`tel:${business.phoneDisplay}`}>{business.phoneDisplay}</a><Button href={wa('Hello, I would like to make an enquiry.')} variant="gold">Chat on WhatsApp <ArrowUpRight size={15}/></Button></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {business.name}</span><span>Professional service. Personal guidance.</span></div></footer>;
}
export function PageShell({ children }) { const { pathname } = useLocation(); return <><Navbar/><main><AnimatePresence mode="wait" initial={false}><motion.div key={pathname} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: 0.22 }}>{children}</motion.div></AnimatePresence></main><Footer/><a className="floating-wa" href={wa('Hello, I would like to make an enquiry.')} target="_blank" rel="noreferrer" aria-label="Chat with us on WhatsApp">✆</a></>; }
export function Hero() {
  return <section className="hero"><div className="hero-image" role="img" aria-label="God’s Grace Mega training vehicle in motion"/><div className="hero-shade"/><div className="hero-content"><Reveal><div className="hero-location"><span/> LAGOS · BADAGRY, NIGERIA</div><h1>Confidence begins<br/>when you <em>take the wheel.</em></h1><p>Learn to drive with purpose. Get support with the paperwork. Make your next move with a team that’s here to help.</p><div className="hero-actions"><Button to="/driving-school" variant="gold">Book Driving Lessons <ArrowRight size={17}/></Button><Button href={wa('Hello God’s Grace Mega Driving School Academy, I would like to enquire about driving lessons.')} variant="outline-light">Chat on WhatsApp <ArrowUpRight size={16}/></Button></div><div className="hero-trust"><ShieldCheck size={18}/><span>Federal Government Approved Driving School with FRSC</span></div></Reveal></div><div className="hero-foot"><span>01 / DRIVE WITH CONFIDENCE</span><a href="#welcome">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>;
}
export function TrustStrip() { return <div className="trust-strip"><div><BadgeCheck/><span><b>Federal Government Approved</b><small>Driving School with FRSC</small></span></div><div><CarFront/><span><b>Manual & Automatic</b><small>Practical driving training</small></span></div><div><ClipboardList/><span><b>More than driving</b><small>Documentation & vehicle support</small></span></div><div><House/><span><b>Local knowledge</b><small>Lagos / Badagry, Nigeria</small></span></div></div>; }
export function CourseCard({ course }) { return <article className="course-card"><div className="course-photo"><img src={imageUrl(course.image, 900)} alt={`${course.type} driving lesson vehicle`} loading="lazy"/><span className="course-tag">{course.type.toUpperCase()} TRAINING</span></div><div className="course-info"><div className="course-top"><h3>{course.type} driving</h3><b>{course.price}</b></div><p>{course.description}</p><ul>{course.features.map(x => <li key={x}><Check size={15}/>{x}</li>)}</ul><Button href={wa(`Hello, I would like to book ${course.type.toLowerCase()} driving training.`)} variant="dark">Enquire about {course.type} <ArrowRight size={16}/></Button></div></article>; }
export function ServiceIcon({ index }) { const icons = [CarFront, ClipboardList, ShieldCheck, Clock3, BadgeCheck, Check]; const Icon = icons[index % icons.length]; return <span className="service-icon"><Icon size={21}/></span>; }
export function ServiceCard({ title, copy, index = 0 }) { return <article className="service-card"><ServiceIcon index={index}/><span className="service-number">0{index + 1}</span><h3>{title}</h3><p>{copy}</p><a href={wa(`Hello, I would like assistance with ${title.toLowerCase()}.`)} target="_blank" rel="noreferrer" className="text-link">Get assistance <ArrowUpRight size={16}/></a></article>; }
export function ImagePanel({ src, alt, label }) { return <div className="image-panel"><img src={src} alt={alt} loading="lazy"/><span>{label}</span></div>; }
export function CTASection({ title = 'Ready for your next move?', copy = 'Talk to our team about lessons, documents, vehicles or property enquiries.', dark = true }) { return <section className={`cta-band ${dark ? 'cta-dark' : ''}`}><div><span className="eyebrow">LET’S GET STARTED</span><h2>{title}</h2><p>{copy}</p></div><Button href={wa('Hello God’s Grace Mega Driving School Academy, I would like to make an enquiry.')} variant="gold">Start a conversation <ArrowRight size={16}/></Button></section>; }
export function Gallery() { const pics = [['practice','Student behind the wheel during driving practice'],['vehicle','God’s Grace Mega training vehicle in motion'],['instructor','Driving student seated behind the wheel'],['automatic','God’s Grace Mega automatic training vehicle']]; return <div className="gallery-grid">{pics.map(([file, alt], i) => <figure key={file} className={`gallery-item gallery-${i + 1}`}><img src={imageUrl(file)} alt={alt} loading="lazy"/><figcaption><span>0{i + 1}</span>{alt}</figcaption></figure>)}</div>; }
const testimonialSamples = [
  { image: 'testimonial1.avif', name: 'Tunde Adebayo', quote: 'The lessons helped me get more comfortable behind the wheel, one step at a time.' },
  { image: 'testimonial2.avif', name: 'Adaeze Okafor', quote: 'I appreciated the flexible schedule and having time to practise the basics.' },
  { image: 'testimonial3.webp', name: 'Ibrahim Musa', quote: 'The training gave me a clearer understanding of the road and the car.' },
];
export function TestimonialCards() { return <div className="testimonial-grid">{testimonialSamples.map(({ image, name, quote }) => <article className="testimonial-card" key={image}><div className="testimonial-card-top"><img src={imageUrl(image)} alt={`Sample testimonial photo for ${name}`} loading="lazy"/><small>SAMPLE REVIEW</small><span>“</span></div><blockquote>{quote}</blockquote><div className="testimonial-card-bottom"><strong>{name}</strong></div></article>)}</div>; }
export function ContactForm() { const [sent, setSent] = useState(false); const submit = (e) => { e.preventDefault(); const data = new FormData(e.currentTarget); const message = `Hello, my name is ${data.get('name')} and my phone number is ${data.get('phone')}. I would like to enquire about ${data.get('topic')}. ${data.get('message')}`; window.open(wa(message), '_blank', 'noopener,noreferrer'); setSent(true); }; return <form className="contact-form" onSubmit={submit}><div className="form-row"><label>Your name<input name="name" autoComplete="name" required placeholder="Full name"/></label><label>Phone number<input name="phone" autoComplete="tel" required placeholder="080…"/></label></div><label>What can we help with?<select name="topic" defaultValue="Driving lessons"><option>Driving lessons</option><option>Vehicle documentation</option><option>Buying or selling a vehicle</option><option>Real estate enquiry</option><option>Other enquiry</option></select></label><label>Your message<textarea name="message" rows="4" required placeholder="Tell us a little about what you need…"/></label><button className="button button-dark" type="submit">{sent ? 'Continue in WhatsApp' : 'Send enquiry'} <ArrowRight size={16}/></button><small>Submitting opens WhatsApp with your enquiry ready to send.</small></form>; }
export function ProcessSteps() { const steps = ['Choose your training','Book your lessons','Complete practical training','Build road confidence','Complete the academy process','Receive your learner’s permit']; return <div className="process-grid">{steps.map((s,i)=><Reveal key={s} delay={i*.05}><div className="process-step"><span>0{i+1}</span><h3>{s}</h3></div></Reveal>)}</div>; }
